### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by demontech** [ravi18011991/smartcertificate#1]
First let me congratulate you about this plugin, really nice work.

I'm getting this every time I click on "Get your certificate", 

500 Server Error

A misconfiguration on the server caused a hiccup. Check the server logs, fix the problem, then try again.
URL: http://moodlesite/mod/smartcertificate/view.php?id=10&action=get

but I can see the certificate from the report. It displays the pdf certificate. I have not setup the Linkedin.

**Comment by ravi18011991** [comment]
Hello demontech,

First of all i would like to say thanks, In smart certificate report features is only used by administrator and teacher for view details of all student who downloaded our certificate,means Administrator and Teacher are able to view all details of student who downloaded our certificate  with student certificate link, Date received , email etc.
please suggest all issues regarding of smart certificate on official git hub link
"https://github.com/vidyamantra/moodle-mod_smartcertificate", where i can reply.
